# Site settings
title: Hansen's Blog                # 你的博客网站标题
SEOTitle: Hansen's Blog | 汉生的博客  # 在后面会详细谈到
description: "Hansen's Blog"        # 随便说点，描述一下

# SNS settings      
github_username: dgynfi           # 你的github账号
weibo_username: u/2617525300      # 你的微博账号，底部链接会自动更新的。

# Build settings
# paginate: 10                    # 一页你准备放几篇文章
